- name: install nginx
  hosts: WEB
  become: ture #key word for privilage escalations use sudo in terminal
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: httpd
        state: latest