- name: variable
  hosts: local host
  connection: local
  vars:
    URL: play.google.com
  tasks:
      - name: print variable
        ansible.builtin.debug:
          msg: URL = {{URL}}
#ansible access variable with two flower braces
      - name: print task variable
        ansible.builtin.debug:
          msg: URL = {{URL}}
          vars:
            URL: tasks.google.com
