- name: demo on conditions
  hosts: all
  connection: local
  tasks:
    - name: print
      ansible.builtin.debug:
        msg: fruits name - apple

    - name: print
      ansible.builtin.debug:
        msg: vegetable name - carrot